# https://taskfile.dev

version: '3'

vars:
  PROJECT: w1termos

tasks:

  default:
    dir: src
    desc: run app
    cmds:
      - dotenv -f ../.env run mamba run -n {{.PROJECT}} python -m {{.PROJECT}}.cli {{.CLI_ARGS}}
    silent: true

  logs:
    desc: monitor logs
    cmds:
      - ssh pi4 'source ~/.bashrc;journalctl --unit {{.PROJECT}} -f --all'

  export:
    desc: export env
    cmds:
      - conda env export --no-builds  -n {{.PROJECT}} > environment.yml

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  pull:
    desc: pulls from git
    cmds:
      - dotenv run ssh pi4 'source ~/.bashrc;cd /storage/src/{{.PROJECT}};git reset --hard;git pull'

  pp:
    desc: push and pull
    cmds:
      - task: push
      - task: pull

  build:
    desc: build
    cmds:
      - rm -rf build
      - rm -rf dist/*
      - mamba run -n {{.PROJECT}} python  -m build

  publish:
    desc: publish
    cmds:
      - scp dist/* muzak:/var/www/pypi/packages/{{.PROJECT}}

  run:
    desc: systemd exec
    dir: src/
    cmds:
      - dotenv -f ../.env run mamba run --live-stream -n {{.PROJECT}} python -m {{.PROJECT}}

  start:
    desc: start the service
    cmds:
      - ssh pi4 'source ~/.bashrc;systemctl start {{.PROJECT}}'

  stop:
    desc: stop the server
    cmds:
      - ssh pi4 'source ~/.bashrc;systemctl stop {{.PROJECT}}'

  restart:
    desc: restart the service
    cmds:
      - task: stop
      - ssh pi4 'source ~/.bashrc;sleep 1'
      - task: start

  deploy:
    desc: all
    cmds:
      - task: stop
      - task: pp
      - task: start
