# https://taskfile.dev

version: '3'

vars:
  PROJECT: w1termos

tasks:

  default:
    dir: src
    desc: run app
    cmds:
      - dotenv -f ../.env run mamba run -n {{.PROJECT}} python -m {{.PROJECT}}.cli {{.CLI_ARGS}}
    silent: true

  logs:
    desc: monitor logs
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;journalctl --user-unit {{.PROJECT}} -f --all'

  export:
    desc: export env
    cmds:
      - conda env export --no-builds  -n {{.PROJECT}} > environment.yml

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  pull:
    desc: pulls from git
    cmds:
      - dotenv run ssh {{.REMOTE_HOST}} 'source ~/.bashrc;cd /storage/src/{{.PROJECT}};git reset --hard;git pull'

  pp:
    desc: push and pull
    cmds:
      - task: push
      - task: pull

  build:
    desc: build
    cmds:
      - rm -rf build
      - rm -rf dist/*
      - mamba run -n {{.PROJECT}} python  -m build

  publish:
    desc: publish
    cmds:
      - scp dist/* muzak:/var/www/pypi/packages/{{.PROJECT}}

  run:
    desc: systemd exec
    dir: src/
    cmds:
      - dotenv -f ../.env run mamba run -n {{.PROJECT}} python -m {{.PROJECT}}


  deploy:
    desc: all
    cmds:
      - task: push
      - task: build
      - task: publish
